# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-24 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=20)),
                ('picture', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='pictures')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
