# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-10-22 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='dealer',
            new_name='seller',
        ),
    ]
