# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-12-06 06:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='make', chained_model_field='make', on_delete=django.db.models.deletion.CASCADE, to='gari.Model'),
        ),
    ]
