# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-10-27 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0002_auto_20201022_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='gari', max_length=200),
        ),
    ]
