# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-12-08 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0003_auto_20201206_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('black', 'Black')], max_length=100),
        ),
    ]
