# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-11-05 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0003_vehicle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='county',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gari.County'),
        ),
    ]
