# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-11-05 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0004_auto_20201105_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='county',
            field=models.CharField(choices=[('kirinyaga', 'Kirinyaga'), ('nairobi', 'Nairobi'), ('mombasa', 'Mombasa')], default='Nairobi', max_length=100),
        ),
    ]
