# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-01-02 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0004_auto_20201208_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('suv', 'Suv'), ('saloon', 'Saloon'), ('coupe', 'Coupe'), ('truck', 'Truck'), ('van', 'Van'), ('pickup', 'Pickup'), ('hatchback', 'Hatchback'), ('estate', 'Estate'), ('convertible', 'Convertible'), ('mvp', 'Mvp'), ('buses', 'Buses'), ('motorbikes', 'Motorbikes')], default='saloon', max_length=100),
        ),
    ]
