# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-01-16 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0007_auto_20210109_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='dealer', max_length=200),
        ),
    ]
