# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-01-22 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0009_profile_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='service',
            field=models.ManyToManyField(blank=True, to='gari.Service'),
        ),
    ]
