# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-01-25 08:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0010_auto_20210122_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.PositiveIntegerField()),
                ('picture', imagekit.models.fields.ProcessedImageField(upload_to='vehicles')),
                ('status', models.CharField(choices=[('used', 'Used'), ('new', 'New'), ('import', 'Import')], max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('black', 'Black')], max_length=100)),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_related', to=settings.AUTH_USER_MODEL)),
                ('counties', models.ManyToManyField(to='gari.County')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gari.Make')),
                ('model', smart_selects.db_fields.ChainedForeignKey(chained_field='make', chained_model_field='make', on_delete=django.db.models.deletion.CASCADE, to='gari.Model')),
            ],
        ),
    ]
