# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-01-25 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0011_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
