# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-01-26 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0012_auto_20210125_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gari.Profile')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gari.Quote')),
            ],
        ),
    ]
