# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-01-30 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0014_auto_20210126_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='logo',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
