# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-01-30 06:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0015_make_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='make',
            name='slug',
            field=models.SlugField(default='vehicle', max_length=200),
        ),
    ]
