# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-01-31 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0016_auto_20210130_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='description',
            field=models.TextField(default='A Good brand'),
        ),
    ]
