# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-01-31 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0017_make_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='description',
            field=models.TextField(default='A superb model'),
        ),
        migrations.AddField(
            model_name='model',
            name='higher_price',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='model',
            name='lower_price',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='model',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='vehicles'),
        ),
    ]
