# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-02-02 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0021_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='makes',
            field=models.ManyToManyField(to='gari.Make'),
        ),
    ]
