# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-02-02 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0022_profile_makes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='makes',
            field=models.ManyToManyField(blank=True, to='gari.Make'),
        ),
    ]
