# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-02-02 16:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0023_auto_20210202_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
