# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-02-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0024_blog_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gari.Type'),
        ),
    ]
