# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-02-05 06:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0025_auto_20210204_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(default='type', max_length=200),
        ),
    ]
