# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-02-05 06:55
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0026_auto_20210205_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='agents'),
        ),
    ]
