# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-02-06 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0027_type_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='client',
        ),
        migrations.AddField(
            model_name='quote',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='quote',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
