# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-02-12 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0029_auto_20210206_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='model',
            name='slug',
            field=models.SlugField(default='model', max_length=200),
        ),
    ]
