# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-07-15 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0030_auto_20210212_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='deal_deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 14, 7, 32, 990000)),
        ),
    ]
