# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-07-16 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import gari.models


class Migration(migrations.Migration):

    dependencies = [
        ('gari', '0031_vehicle_deal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='deal_deadline',
            field=models.DateField(default=gari.models.get_deadline),
        ),
    ]
